name: CI
on: [push]
jobs:
  php:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.2', '8.3', '8.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with Composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: cs2pr
          coverage: xdebug

      - name: Install Composer dependencies
        run: composer install --no-interaction --classmap-authoritative --no-suggest --no-progress

      - name: Run PHPUnit tests
        run: php vendor/bin/phpunit -c phpunit.xml --coverage-text=coverage.txt && if [ $(head -9 coverage.txt | tail -3 | cut -d "%" -f1 | sed 's/[^0-9.]//g' | tr -d '\n') != "100.00100.00100.00" ]; then cat coverage.txt; exit 1; fi

      - name: Run PHP CS Fixer (Dry Run)
        run: PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer fix --dry-run --allow-risky=yes --using-cache=no --format=checkstyle | cs2pr --graceful-warnings
